image: thinkr/runnerci
test:
  script:
  - R -e 'install.packages("kableExtra")'
  - R -e 'install.packages("skimr")'
  - R CMD build . --no-build-vignettes --no-manual
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R -e 'devtools::check()'
  - R -e 'devtools::test()'

