usethis::use_package("arsenal")
usethis::use_package("dplyr")
usethis::use_package("glue")
usethis::use_package("tibble")
usethis::use_package("stringr")
usethis::use_package("forcats")
Busethis::use_tidy_eval()
usethis::use_pipe()
usethis::use_data_raw()
usethis::use_tidy_description()
usethis::use_vignette("demo")
usethis::use_vignette("demo2")

usethis::use_git()
usethis::use_github()
