---
title: "demo2"
author: "Vincent"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
vignette: >
  %\VignetteIndexEntry{demo2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r message=FALSE, warning=FALSE}
library(cloudy)
library(dplyr)
library(skimr)
library(tibble)
```

# Import de la base
```{r message=FALSE, warning=FALSE}
library(tidyverse)
dataset <- structure(list(id = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), age = c(12, 
43, NA, 21, 2, 56, 7, 8, 9, 3), sexe = c("F", "F", "M", NA, "F", 
"M", "M", "F", "F", "M"), `tu fume ?` = c("non", "non", "oui", 
"oui", "non", "oui", NA, "non", "non", "oui"), `tu fume combien ?` = c(NA, 
NA, 2, 3, NA, NA, NA, NA, NA, 5), `date des derniere regles` = structure(c(1496361600, 
1493942400, NA, 1493942400, 1485907200, 1496448000, NA, 1496448000, 
NA, NA), class = c("POSIXct", "POSIXt"), tzone = "UTC"), `ca va ?` = c("oui", 
"non", "oui", "non", "non", "non", "non", "oui", "oui", "oui"
)), .Names = c("id", "age", "sexe", "tu fume ?", "tu fume combien ?", 
"date des derniere regles", "ca va ?"), class = c("tbl_df", "tbl", 
"data.frame"), row.names = c(NA, -10L))


```



# Statistiques descriptives

## variables quantitatives
```{r include=FALSE}
sk <- skim(dataset)
tableau_quanti <-  sk %>% 
  filter(type %in% c("integer","numeric")) %>%
  dplyr::do(., skimr:::skim_render(., NULL, skimr:::print_impl)) 
 
```

```{r eval=TRUE}
tableau_quanti %>% 
  select(-hist) %>% 
  DT::datatable()

```


## Variables qualitatives

```{r results='asis' , message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(purrr)
quali <- dataset %>% 
  map_chr(~class(.x)[[1]]) %>% 
  .[.%in% c("character","factor")] %>% 
  names()



for (var in quali){
  cat("###   ", var, "\n   ") 
  cat("\n")
  cat("\n")
  # dataset[[var]]
  dataset %>% quali_desc_(var)

}
  
```


